name: Backend CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Set this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Notify Render for Deployment
      run: 'curl -X POST https://api.render.com/webhooks/YOUR_RENDER_WEBHOOK_ID'
